name: General Issue
description: Report a bug, request a feature, or ask a question.
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to open an issue! Please fill out the sections below so we can understand and address your report.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - Bug
        - Feature Request
        - Question
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue or request.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: If this is a bug, list the steps to reproduce the behavior.
      placeholder: |
        1. Start the MCP server with '...'
        2. Call tool '...' with input '...'
        3. Observe error '...'
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages or logs.
    validations:
      required: false

  - type: input
    id: server-version
    attributes:
      label: Server Version
      description: The version or commit hash of the MCP server you are using.
      placeholder: e.g., 1.2.0 or abc1234
    validations:
      required: false

  - type: dropdown
    id: transport
    attributes:
      label: Transport
      description: Which transport are you using?
      options:
        - stdio
        - HTTP
        - Both (stdio + HTTP)
    validations:
      required: false

  - type: input
    id: mcp-client
    attributes:
      label: MCP Client
      description: Which MCP client are you using (e.g., VS Code + GitHub Copilot, Claude Desktop, MCP Inspector)?
      placeholder: e.g., VS Code with GitHub Copilot
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help.
    validations:
      required: false
